name: generate asci

on: push

jobs:
    asci_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6
            
            - name: run bash script
              run: ./asci-script.sh

            