name: my first action

on: push

jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6
              
            - name: list files and read
              run: |
                echo "my first acton"
                ls -la
                cat README.md
            
