name: my first action

on: push

jobs:
    my-job:
        runs-on: ubuntu-lates
        steps:
            - name: my first action
              run: echo "my first acton"

            - name: list files
              run: ls
            
            - name: read file
              run: cat README.md
